Update OpenAI translator
TareHimself/manga-translator pull request #42
Opened 2024-03-17 13:45 UTC by windbow27

Howdy, 

I would like to thank you for making this. I have been looking around, tried various repos like cotrans and similar but those weren't really suit my needs. Until I found yours, that is.

However, I encountered an issue with the OpenAI translator. After some troubleshooting, I managed to resolve the issue and decided to create a pull request.

# Description

- Fix OpenAI error:
  `You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run openai migrate to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. pip install openai==0.28 A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742`

# Changes

1. Changed `ChatCompletion` to `chat.completions` and related codes.
2. Because I found CLI kinda confusing at first, I added `usage` . Please take a look.
    I usually download doujinshi as a folder. So CLI is my best option. Basically create img/translate folder and put images there, run the command and the whole folder will be translated. I tried putting many folders at once and it was a mess, so I think there are improvements to be made.
3. I didn't download color detection, and the traceback print was kinda annoying, so I commented it and replace with a print.
4. For some reasons, it prints some errors that I don't have cuda instead of choosing cpu. I modifed that part a bit.

# Note
- I should have pulled dev branch and made changes there. But wellll...
- **I'm not used to python, so this could be totally unnecessary and could be fixed by doing something I'm not aware 😅.** 
- Sometimes huggingface will display this, but I assume this is the translator's fault. Same for OpenAI, it is way more apparent with "Sorry I can't understand yada yada"
![ja_oshi_no_ko_converted](https://github.com/TareHimself/manga-translator/assets/59176912/2c47279b-6f38-4723-be09-d781dfaeef30)

2024-03-21 20:43 UTC, TareHimself requested changes
The device for color detection has been updated in the dev branch so if you can remove that from your changes then I can merge this, and yes int the future it would be preferable if you could fork from and merge to dev

2024-03-21 21:30 UTC, TareHimself commented
Also have you confirmed that sending the model ```{
                    "role": "system",
                    "content": "You are a helpful assistant."
                },
                {
                    "role": "user",
                    "content": message
                }``` Works better than giving it an example?

2024-03-22 01:03 UTC, windbow27 commented
Removed. I did some brief testings and no, it actually isn't better, reverted that too.

2024-03-23 10:16 UTC, TareHimself approved these changes

2024-03-23 10:17 UTC, merged